language: java

jdk:
  - openjdk8

services:
  - postgresql
addons:
  postgresql: "9.4"
  notification_email: nguyenthienthuat92@gmail.com

cache:
  - gradle
  - gradlewrapper

before_script:
  - psql -c 'create database authentication_ntthuat;' -U postgres

script:
  - ./gradlew build