apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 1

  # FIXME: remove this in the next version
  selector:
    matchLabels:
      app: authentication

  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: 10.30.1.18:32000/ecoms/authentication:$BUILD_NUMBER
        ports:
        - containerPort: 8080
