apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication
  labels:
    app: authentication
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  application.yaml: |-
    spring:
      datasource:
        url: jdbc:postgresql://authentication-postgresql:5432/postgres
        username: postgres
        password: postgres
    logging.level:
      org.springframework.web: INFO
      org.apache.tomcat: INFO
      org.hibernate.SQL: DEBUG